# Generated by Django 3.2.7 on 2021-09-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('in_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=40)),
                ('project', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMaster',
            fields=[
                ('in_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dt_utc_start_time', models.DateTimeField()),
                ('dt_utc_end_time', models.DateTimeField()),
                ('in_mouse_count', models.IntegerField()),
                ('in_keyboard_count', models.IntegerField()),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('st_manual_entry_reason', models.CharField(max_length=100)),
                ('is_idle_mode', models.BooleanField(default=False)),
                ('in_screenshot_count', models.IntegerField()),
                ('in_webcam_count', models.IntegerField()),
                ('in_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_master', to='api.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityChild',
            fields=[
                ('in_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dt_utc_start_time', models.DateTimeField()),
                ('dt_utc_end_time', models.DateTimeField()),
                ('in_mouse_count', models.IntegerField()),
                ('in_keyboard_count', models.IntegerField()),
                ('in_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_child', to='api.activitymaster')),
            ],
        ),
    ]
