# Generated by Django 3.2.7 on 2021-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activity_in_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='in_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
