# Generated by Django 3.2.7 on 2021-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activitymaster_st_manual_entry_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitychild',
            name='in_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
